//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RockPaperScissors {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GameResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GameResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RockPaperScissors.GameResources", typeof(GameResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Please press a key to indicate your next hand.
        ///Key: R = Rock, P = Paper, S = Scissors
        ///.
        /// </summary>
        internal static string ChooseHand {
            get {
                return ResourceManager.GetString("ChooseHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the number of players, 1 or 2?
        ///.
        /// </summary>
        internal static string ChoosePlayerNumbers {
            get {
                return ResourceManager.GetString("ChoosePlayerNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {0} chose {1},
        ///Player {2} chose {3}
        ///
        ///{4}
        ///
        ///So the winner is...
        ///
        ///Player {5}
        ///
        ///
        ///.
        /// </summary>
        internal static string DeclareResults {
            get {
                return ResourceManager.GetString("DeclareResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for playing!
        ///.
        /// </summary>
        internal static string EndBanner {
            get {
                return ResourceManager.GetString("EndBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the name for player {0}.
        /// </summary>
        internal static string EnterNames {
            get {
                return ResourceManager.GetString("EnterNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input, please enter one of the following: {0}.
        /// </summary>
        internal static string InvalidInputText {
            get {
                return ResourceManager.GetString("InvalidInputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to play again?
        ///(Y or N)
        ///.
        /// </summary>
        internal static string PlayAgainPrompt {
            get {
                return ResourceManager.GetString("PlayAgainPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player 2 will be the CPU
        ///.
        /// </summary>
        internal static string Player2isCPU {
            get {
                return ResourceManager.GetString("Player2isCPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Rock Paper Scissors
        ///Press Ctrl+C to end at any time
        ///
        ///Game Rules:
        ///
        ///A match takes place between 2 players and is made up of 3 games, with the overall winner being the first player to win 2 games (i.e. best of 3).
        ///Each game consists of both players selecting one of Rock, Paper or Scissors; the game winner is determined based on the following rules:
        ///
        ///* Rock beats scissors
        ///* Scissors beats paper
        ///* Paper beats rock
        ///
        ///.
        /// </summary>
        internal static string WelcomeBanner {
            get {
                return ResourceManager.GetString("WelcomeBanner", resourceCulture);
            }
        }
    }
}
